# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  chatbotapi:
    image: chatbotapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5204:5204
      - 7139:7139
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
