using System.Collections.Generic;

public static class LanguageCodeMappingUtil
{
    public static Dictionary<string, string> Iso639_3ToGcp = new Dictionary<string, string>
    {
        {"ara", "ar-XA"},
        {"ben", "bn-IN"},
        {"cmn", "cmn-CN"},
        {"ces", "cs-CZ"},
        {"dan", "da-DK"},
        {"deu", "de-DE"},
        {"ell", "el-GR"},
        {"eng", "en-GB"},
        {"spa", "es-ES"},
        {"fin", "fi-FI"},
        {"fil", "fil-PH"},
        {"fra", "fr-CA"},
        {"guj", "gu-IN"},
        {"hin", "hi-IN"},
        {"hun", "hu-HU"},
        {"ind", "id-ID"},
        {"ita", "it-IT"},
        {"jpn", "ja-JP"},
        {"kor", "ko-KR"},
        {"lit", "lt-LT"},
        {"lav", "lv-LV"},
        {"msa", "ms-MY"},
        {"mar", "mr-IN"},
        {"nld", "nl-NL"},
        {"nob", "nb-NO"},
        {"pol", "pl-PL"},
        {"por", "pt-PT"},
        {"pan", "pa-IN"},
        {"ron", "ro-RO"},
        {"rus", "ru-RU"},
        {"slk", "sk-SK"},
        {"slv", "sl-SI"},
        {"swe", "sv-SE"},
        {"tam", "ta-IN"},
        {"tel", "te-IN"},
        {"tha", "th-TH"},
        {"tur", "tr-TR"},
        {"ukr", "uk-UA"},
        {"urd", "ur-IN"},
        {"vie", "vi-VN"},
        {"xho", "xh-ZA"},
        {"zul", "zu-ZA"},
    };
}
