using System.Collections.Generic;

public static class LanguageCodeMappingUtil
{
    public static Dictionary<string, string> Iso639_3ToGcp = new Dictionary<string, string>
    {
        {"ara", "ar-XA"},
        {"ben", "bn-IN"},
        {"cmn", "cmn-CN"},
        {"ces", "cs-CZ"},
        {"dan", "da-DK"},
        {"deu", "de-DE"},
        {"ell", "el-GR"},
        {"eng", "en-US"},
        {"spa", "es-ES"},
        {"fin", "fi-FI"},
        {"fil", "fil-PH"},
        {"fra", "fr-CA"},
        {"guj", "gu-IN"},
        {"hin", "hi-IN"},
        {"hun", "hu-HU"},
        {"ind", "id-ID"},
        {"ita", "it-IT"},
        {"jpn", "ja-JP"},
        {"kor", "ko-KR"},
        {"lit", "lt-LT"},
        {"lav", "lv-LV"},
        {"msa", "ms-MY"},
        {"mar", "mr-IN"},
        {"nld", "nl-NL"},
        {"nob", "nb-NO"},
        {"pol", "pl-PL"},
        {"por", "pt-PT"},
        {"pan", "pa-IN"},
        {"ron", "ro-RO"},
        {"rus", "ru-RU"},
        {"slk", "sk-SK"},
        {"slv", "sl-SI"},
        {"swe", "sv-SE"},
        {"tam", "ta-IN"},
        {"tel", "te-IN"},
        {"tha", "th-TH"},
        {"tur", "tr-TR"},
        {"ukr", "uk-UA"},
        {"urd", "ur-IN"},
        {"vie", "vi-VN"},
        {"xho", "xh-ZA"},
        {"zul", "zu-ZA"},
    };

    public static Dictionary<string, string> Iso639_1ToGcp = new Dictionary<string, string>
{
    {"ar", "ar-XA"},
    {"bn", "bn-IN"},
    {"zh", "cmn-CN"},
    {"cs", "cs-CZ"},
    {"da", "da-DK"},
    {"de", "de-DE"},
    {"el", "el-GR"},
    {"en", "en-US"},
    {"es", "es-ES"},
    {"fi", "fi-FI"},
    {"fil", "fil-PH"},
    {"fr", "fr-CA"},
    {"gu", "gu-IN"},
    {"hi", "hi-IN"},
    {"hu", "hu-HU"},
    {"id", "id-ID"},
    {"it", "it-IT"},
    {"ja", "ja-JP"},
    {"ko", "ko-KR"},
    {"lt", "lt-LT"},
    {"lv", "lv-LV"},
    {"ms", "ms-MY"},
    {"mr", "mr-IN"},
    {"nl", "nl-NL"},
    {"nb", "nb-NO"},
    {"pl", "pl-PL"},
    {"pt", "pt-PT"},
    {"pa", "pa-IN"},
    {"ro", "ro-RO"},
    {"ru", "ru-RU"},
    {"sk", "sk-SK"},
    {"sl", "sl-SI"},
    {"sv", "sv-SE"},
    {"ta", "ta-IN"},
    {"te", "te-IN"},
    {"th", "th-TH"},
    {"tr", "tr-TR"},
    {"uk", "uk-UA"},
    {"ur", "ur-IN"},
    {"vi", "vi-VN"},
    {"xh", "xh-ZA"},
    {"zu", "zu-ZA"},
};


}
